name: "Checks for Github Actions"
description: "Run dagger checks in Github Actions"
inputs:
  version:
    description: "Dagger Version. Use semver vX.Y.Z or 'latest'"
    required: false
    default: "latest"
  commit:
    description: "Dagger Dev Commit"
    required: false
    default: ""
  progress:
    description: "Dagger progress format"
    required: false
    default: "dots"
  dagger-flags:
    description: "Dagger CLI Flags"
    required: false
    default: ""
  workdir:
    description: "The working directory in which to run the Dagger CLI"
    required: false
    default: "."
  cloud-token:
    description: "Dagger Cloud Token"
    required: false
    default: ""
  module:
    description: "Dagger module to call. Local or Git"
    required: false
    default: ""
  filter:
    description: "Filter to apply to checks"
    required: false
    default: "**"
  summary-path:
    description: "File path to write the job summary"
    required: false
    default: ""
  enable-github-summary:
    description: "Whether to write summary to GITHUB_STEP_SUMMARY"
    required: false
    default: "false"
outputs:
  output:
    description: "Job output"
    value: ${{ steps.exec.outputs.stdout }}
  traceURL:
    description: "Dagger Cloud trace URL"
    value: ${{ steps.exec.outputs.traceURL }}
runs:
  using: "composite"
  steps:
    # Not all inputs are available in last tagged release. So we pin to main as of 2025-nov-17
    - uses: dagger/dagger-for-github@662d9b66af7c40b8745fb3131785a53129193ffe
      env:
        DAGGER_PROGRESS: ${{ inputs.progress }}
      with:
        verb: checks
        args: ${{ inputs.filter }}
        version: ${{ inputs.version }}
        commit: ${{ inputs.commit }}
        dagger-flags: ${{ inputs.dagger-flags }}
        workdir: ${{ inputs.workdir }}
        cloud-token: ${{ inputs.cloud-token }}
        module: ${{ inputs.module }}
        summary-path: ${{ inputs.summary-path }}
        enable-github-summary: ${{ inputs.enable-github-summary }}
