name: "Checks for Github Actions"
description: "Run dagger checks in Github Actions"
inputs:
  version:
    description: "Dagger Version. Use semver vX.Y.Z or 'latest'"
    required: false
    default: "latest"
  commit:
    description: "Dagger Dev Commit"
    required: false
    default: ""
  progress:
    description: "Dagger progress format"
    required: false
    default: "dots"
  workdir:
    description: "The working directory in which to run the Dagger CLI"
    required: false
    default: "."
  cloud-token:
    description: "Dagger Cloud Token"
    required: false
    default: ""
  module:
    description: "Dagger module to call. Local or Git"
    required: false
    default: ""
  filter:
    description: "Filter to apply to checks"
    required: false
    default: "**"
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        set -o pipefail
        # Fallback to /usr/local for backwards compatability
        prefix_dir="${RUNNER_TEMP:-/usr/local}"
        # Ensure the dir is writable otherwise fallback to tmpdir
        if [[ ! -d "$prefix_dir" ]] || [[ ! -w "$prefix_dir" ]]; then
            prefix_dir="$(mktemp -d)"
        fi
        printf '%s/bin' "$prefix_dir" >> $GITHUB_PATH

        # If the dagger version is 'latest', set the version back to an empty
        # string. This allows the install script to detect and install the latest
        # version itself
        VERSION=${{ inputs.version }}
        if [[ "$VERSION" == "latest" ]]; then
          VERSION=
        elif [[ -n "$VERSION" && "$VERSION" != v* ]]; then
          # Add 'v' prefix if version doesn't start with 'v' and is not empty
          VERSION="v$VERSION"
        fi
        latest=$(curl https://dl.dagger.io/dagger/versions/latest)

        COMMIT=${{ inputs.commit }}

        if [[ -x "$(command -v dagger)" ]]; then
          echo "::group::Checking dagger"
          version="$(dagger --silent version | cut --fields 2 --delimiter ' ')"
          echo "Found existing dagger version: $version"
          if [[ "$version" == "$VERSION" ]] || [[ "$version" == "$latest" ]]; then
            echo "dagger ${version} is already installed, skipping installation"
            exit 0
          fi
          echo "::endgroup::"
        fi

        echo "::group::Installing dagger"
        curl -fsSL https://dl.dagger.io/dagger/install.sh | \
        BIN_DIR=${prefix_dir}/bin DAGGER_VERSION="$VERSION" DAGGER_COMMIT="$COMMIT" sh
        echo "::endgroup::"
    - id: exec
      shell: bash
      env:
        DAGGER_MODULE: ${{ inputs.module }}
        DAGGER_PROGRESS: ${{ inputs.progress }}
        DAGGER_CLOUD_TOKEN: ${{ inputs.cloud-token }}
      run: |
        cd ${{ inputs.workdir }}
        dagger checks '${{ inputs.filter }}'
